name: Java CI with Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      # 4. Run tests and show results in logs
      - name: Run Tests
        run: mvn test -Dsurefire.printSummary=true

      # 5. Build Docker image (optional: only if tests pass)
      - name: Build Docker image
        run: docker build -t crudapp:latest .
